version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: trendinalia_api
    container_name: trendinalia_api
    ports:
      - 5000:5000
    entrypoint: ['/usr/src/app/entrypoint.sh']
    networks:
    - demo
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: database
    volumes:
      - ./mysql_data/:/var/lib/mysql/
    ports:
      - 3306:3306
    env_file: env_files/mysql.env
    networks:
      - demo

networks:
  demo: